#!/bin/sh

# Copyright (c) [Fendy/WHU] [2025-2026]
# Licensed under the MIT License (the "MIT License");
# You may obtain a copy of the MIT License at:
#   https://opensource.org/licenses/MIT

set -eu

# $1 -- the path of zip file
# $2 -- the path of output (/output/xx-parser_name/xxx.zip/)

filename=$(basename "$1")
src_dir="/workspace/src"
executable="$src_dir/unzip.pl"

echo "Running $executable $1 $2"
rm -rf /workspace/cover_db
log_file=$(mktemp)
if perl -MDevel::Cover=-select,Archive::Zip,-db,/workspace/cover_db "$executable" "$1" "$2" >"$log_file" 2>&1; then
    cat "$log_file"
else
    cat "$log_file"
    rm -f "$log_file"
    exit 1
fi

out_dir="$(dirname "$2")"
percent=$(awk '
    /^Total[[:space:]]/ {
        v=$NF
        if (v ~ /^[0-9]+([.][0-9]+)?$/) {
            print v
            exit
        }
    }
' "$log_file")
rm -f "$log_file"

if [ -z "$percent" ]; then
    /workspace/coverage.sh /workspace/cover_db "$filename" "$out_dir"
else
    printf "%s\n" "$percent" > "$out_dir/$filename.covinfo"
fi
