#!/bin/sh

set -eu

filename=$(basename "$1")
out_dir="$2/.."
src_dir="/workspace"

find "$src_dir" -name "*.gcda" -delete
/workspace/unzip-bin "$1" "$2"

sh /workspace/coverage.sh "$src_dir" "$filename" "$out_dir"
