#!/bin/sh

set -eu

filename=$(basename "$1")
cov_dir=$(mktemp -d 2>/dev/null || mktemp -d -t jacoco)
exec_file="$cov_dir/jacoco.exec"

trap 'rm -rf "$cov_dir"' EXIT

java -javaagent:/tools/jacocoagent.jar=destfile="$exec_file",append=false,includes=unzip/* \
    -jar /workspace/unzip.jar "$1" "$2"

export JACOCO_CLASSFILES="/workspace/classes"
/workspace/coverage.sh "$exec_file" "unzip" "$filename" "$2/.." || printf "0\n" > "$2/../$filename.covinfo"
