#!/bin/sh

# Copyright (c) [Fendy/WHU] [2025-2026]
# Licensed under the MIT License (the "MIT License");
# You may obtain a copy of the MIT License at:
#   https://opensource.org/licenses/MIT

set -eu

# $1 -- the path of zip file
# $2 -- the path of output (/output/xx-parser_name/xxx.zip/)

filename=$(basename "$1")
src_dir="/workspace/src"
executable="$src_dir/unzipada"
zip_dir=$(dirname "$1")
zip_file=$(basename "$1")

find "$src_dir" -name "*.gcda" -delete
mkdir -p "$2"
(cd "$zip_dir" && "$executable" -d "$2" "$zip_file")

/workspace/coverage.sh "$src_dir" "$filename" "$2/.."
