#!/bin/sh

set -eu

filename=$(basename "$1")
out_dir="$2/.."

cd "$2"

coverage_result=$(erl -noshell -eval "
cover:start(),
case cover:compile_beam(zip) of
    {ok, zip} -> ok;
    {ok, zip, _Warnings} -> ok;
    Error ->
        io:format(\"ERROR:~p~n\", [Error]),
        erlang:halt(2)
end,
case zip:unzip(\"$1\") of
    {ok, _} -> ok;
    {error, Reason} ->
        io:format(\"UNZIP_ERROR:~p~n\", [Reason]),
        erlang:halt(1)
end,
case cover:analyse(zip, module) of
    {ok, {Covered, NotCovered}} ->
        io:format(\"COVERED=~B NOT_COVERED=~B~n\", [Covered, NotCovered]),
        erlang:halt(0);
    AnalyseError ->
        io:format(\"ANALYSE_ERROR:~p~n\", [AnalyseError]),
        erlang:halt(2)
end.
" -s init stop)

/workspace/coverage.sh "$coverage_result" "$filename" "$out_dir"
