#!/bin/sh

# Copyright (c) [Fendy/WHU] [2025-2026]
# Licensed under the MIT License (the "MIT License");
# You may obtain a copy of the MIT License at:
#   https://opensource.org/licenses/MIT

set -eu

# $1 -- the path of zip file
# $2 -- the path of output (/output/xx-parser_name/xxx.zip/)

filename=$(basename "$1")
src_dir="/workspace/src"
ziptool="$src_dir/build-coverage/src/ziptool"

find "$src_dir" -name "*.gcda" -delete
count=$("$ziptool" "$1" get_num_entries 0 | sed -n 's/^\([0-9][0-9]*\).*/\1/p')
if [ -z "$count" ]; then
    count=0
fi
i=0
while [ "$i" -lt "$count" ]; do
    stat_out=$("$ziptool" "$1" stat "$i")
    name=$(printf "%s\n" "$stat_out" | sed -n "s/^name: '\\(.*\\)'$/\\1/p" | head -n 1)
    if [ -n "$name" ]; then
        case "$name" in
            */)
                mkdir -p "$2/$name"
                ;;
            *)
                mkdir -p "$(dirname "$2/$name")"
                "$ziptool" "$1" cat "$i" > "$2/$name"
                ;;
        esac
    fi
    i=$((i + 1))
done

/workspace/coverage.sh "$src_dir" "$filename" "$2/.."
