#!/bin/sh

set -eu

filename=$(basename "$1")
cov_dir=$(mktemp -d 2>/dev/null || mktemp -d -t jacoco)
exec_file="$cov_dir/jacoco.exec"

trap 'rm -rf "$cov_dir"' EXIT

java -javaagent:/tools/jacocoagent.jar=destfile="$exec_file",append=false,includes=org/zeroturnaround/zip/* \
    -jar /workspace/unzip.jar "$1" "$2"

/workspace/coverage.sh "$exec_file" "org/zeroturnaround/zip" "$filename" "$2/.."
