#!/bin/sh

set -eu

filename=$(basename "$1")
cov_dir=$(mktemp -d /tmp/gocov.XXXXXX)

trap 'rm -rf "$cov_dir"' EXIT

GOCOVERDIR="$cov_dir" /workspace/unarr "$1" "$2"

/workspace/coverage.sh "$cov_dir" "$filename" "$2/.."
