#!/bin/sh

set -eu

filename=$(basename "$1")
cov_dir=$(mktemp -d /tmp/v8cov.XXXXXX)

trap 'rm -rf "$cov_dir"' EXIT

nyc --exclude-node-modules=false --cwd /usr/local/lib/node_modules/extract-zip \
    --temp-dir "$cov_dir/.nyc_output" \
    --report-dir "$cov_dir" \
    --reporter json-summary \
    extract-zip "$1" "$2"
/workspace/coverage.sh "$cov_dir" "/yauzl/" "$filename" "$2/.."