#!/usr/bin/env ruby

require 'coverage'
require 'json'

Coverage.start(lines: true)

ARGV.unshift File.expand_path('src/unzip.rb', __dir__)
load ARGV.shift

zip_name = File.basename(ARGV[0] || 'input.zip')
output_dir = ARGV[1] || '.'
cov_path = File.join(output_dir, 'coverage.json')
File.write(cov_path, JSON.dump(Coverage.result))

system('/workspace/coverage.sh', cov_path, zip_name, File.join(output_dir, '..'))
